<?php
// Translations: key => [English, French, Arabic]. Add a language by adding a column + an entry in $LANGS/$LI.
$LANGS = ['en' => 'EN', 'fr' => 'FR', 'ar' => 'العربية'];
$LI = ['en' => 0, 'fr' => 1, 'ar' => 2];
$LOCALE = ['en' => 'en-US', 'fr' => 'fr-FR', 'ar' => 'ar-u-nu-latn'];
$WEEKSTART = ['en' => 0, 'fr' => 1, 'ar' => 6];
$S = [
'nav_what'=>['What is COVID-19?','Qu’est-ce que la COVID-19 ?','ما هو كوفيد-19؟'],
'nav_prev'=>['Prevention','Prévention','الوقاية'],
'nav_sym'=>['Symptoms','Symptômes','الأعراض'],
'nav_report'=>['Report side effects','Déclarer des effets','التبليغ عن الآثار'],
'nav_login'=>['Doctor login','Espace médecin','دخول الأطباء'],
'nav_dash'=>['Dashboard','Tableau de bord','لوحة التحكم'],
'm_patients'=>['Patients','Patients','المرضى'],
'm_new'=>['New patient','Nouveau patient','مريض جديد'],
'm_export'=>['Export CSV','Exporter en CSV','تصدير CSV'],
'signed_in'=>['Signed in as','Connecté en tant que','مسجّل الدخول باسم'],
'logout'=>['Log out','Se déconnecter','تسجيل الخروج'],
'language'=>['Language','Langue','اللغة'],
'foot'=>['Master’s thesis project, Computer Science Department, Badji Mokhtar University, Annaba. Predictions come from clustering models and support clinical judgment; they are not a diagnosis.','Projet de master, Département d’informatique, Université Badji Mokhtar, Annaba. Les prédictions proviennent de modèles de clustering et appuient le jugement clinique ; elles ne constituent pas un diagnostic.','مشروع ماستر، قسم الإعلام الآلي، جامعة باجي مختار عنابة. التنبؤات صادرة عن نماذج التجميع وهي أداة مساعدة للقرار السريري وليست تشخيصًا.'],
'foot_site'=>['University website','Site de l’université','موقع الجامعة'],
'home_title'=>['Home','Acceuil','الرئيسية'],
'hero_h1'=>['See which side effects a vaccine is likely to cause.','Anticipez les effets secondaires d’un vaccin.','اعرف الآثار الجانبية المتوقعة بعد اللقاح.'],
'hero_lead'=>['Add a patient’s age, vaccine and medical history. Three clustering models place them among similar past cases and rank the side effects that followed.','Saisissez l’âge, le vaccin et les antécédents du patient. Trois modèles de clustering le comparent à des cas similaires et classent les effets secondaires observés.','أدخل عمر المريض ونوع اللقاح والسوابق المرضية. تقارنه ثلاثة نماذج تجميع بحالات سابقة مشابهة وترتّب الآثار الجانبية التي ظهرت.'],
'cta_login'=>['Doctor login','Espace médecin','دخول الأطباء'],
'cta_report'=>['Report side effects','Déclarer des effets','التبليغ عن الآثار'],
'viz_alt'=>['Animated scatter plot: a new patient moves between three clusters of past cases','Nuage de points animé : un nouveau patient se déplace entre trois groupes de cas passés','رسم بياني متحرك: مريض جديد يتنقل بين ثلاث مجموعات من الحالات السابقة'],
'cl_a'=>['Cluster A','Groupe A','المجموعة أ'],'cl_b'=>['Cluster B','Groupe B','المجموعة ب'],'cl_c'=>['Cluster C','Groupe C','المجموعة ج'],
'viz_new'=>['New patient','Nouveau patient','مريض جديد'],
'how_h2'=>['From registration to prediction in three steps','De l’inscription à la prédiction en trois étapes','من التسجيل إلى التنبؤ في ثلاث خطوات'],
's1_t'=>['Register the patient','Enregistrer le patient','سجّل المريض'],
's1_p'=>['Identity, vaccine, dose and chronic conditions, in a short guided form.','Identité, vaccin, dose et maladies chroniques, dans un court formulaire guidé.','الهوية واللقاح والجرعة والأمراض المزمنة في نموذج قصير ومُوجَّه.'],
's2_t'=>['Get a ranked prediction','Obtenir une prédiction classée','احصل على تنبؤ مرتّب'],
's2_p'=>['K-Means, Gaussian Mixture and Agglomerative clustering each score the likely side effects. You see the average and each model’s view.','K-Means, mélange gaussien et clustering agglomératif évaluent chacun les effets probables. Vous voyez la moyenne et l’avis de chaque modèل.','يقيّم كل من K-Means والمزيج الغاوسي والتجميع التراكمي الآثار المحتملة. ترى المتوسط ورأي كل نموذج.'],
's3_t'=>['Record what happened','Enregistrer ce qui s’est passé','سجّل ما حدث فعليًا'],
's3_p'=>['Log the real side effects, their start date and duration so every record stays complete and exportable.','Notez les effets réels, leur date de début et leur durée pour garder des dossiers complets et exportables.','دوّن الآثار الفعلية وتاريخ ظهورها ومدتها لتبقى كل السجلات كاملة وقابلة للتصدير.'],
'covid_h2'=>['What is COVID-19?','Qu’est-ce que la COVID-19 ?','ما هو كوفيد-19؟'],
'covid_p'=>['COVID-19 is a respiratory illness caused by the SARS-CoV-2 virus. It became a global pandemic in 2020 and led to worldwide health and economic crises. Vaccination and public health measures are the main tools used to contain it.','La COVID-19 est une maladie respiratoire causée par le virus SARS-CoV-2. Devenue pandémie mondiale en 2020, elle a provoqué des crises sanitaires et économiques. La vaccination et les mesures de santé publique sont les principaux moyens de la contenir.','كوفيد-19 مرض تنفسي يسببه فيروس سارس-كوف-2. أصبح جائحة عالمية عام 2020 وتسبب بأزمات صحية واقتصادية حول العالم. اللقاح وإجراءات الصحة العامة هما الوسيلتان الرئيسيتان لاحتوائه.'],
'prot_h2'=>['How to protect yourself','Comment se protéger','كيف تحمي نفسك'],'do_h'=>['Do','À faire','افعل'],'avoid_h'=>['Avoid','À éviter','تجنّب'],
'do1'=>['Get vaccinated against COVID-19','Se faire vacciner contre la COVID-19','تلقَّ لقاح كوفيد-19'],
'do2'=>['Wear a mask in crowded or indoor places','Porter un masque dans les lieux fermés ou bondés','ارتدِ الكمامة في الأماكن المغلقة أو المزدحمة'],
'do3'=>['Wash your hands or use sanitizer','Se laver les mains ou utiliser un gel','اغسل يديك أو استخدم المعقّم'],
'do4'=>['Keep your distance from others','Garder ses distances','حافظ على مسافة التباعد'],
'do5'=>['Disinfect surfaces at home','Désinfecter les surfaces à la maison','عقّم الأسطح في المنزل'],
'do6'=>['Stay home when sick or exposed','Rester chez soi en cas de symptômes ou d’exposition','ابقَ في المنزل عند المرض أو المخالطة'],
'av1'=>['Close contact with infected people','Contact étroit avec des personnes infectées','المخالطة القريبة للمصابين'],
'av2'=>['Handshakes','Les poignées de main','المصافحة'],
'av3'=>['Touching your face','Se toucher le visage','لمس الوجه'],
'av4'=>['Contaminated surfaces','Les surfaces contaminées','الأسطح الملوثة'],
'av5'=>['Exposure to droplets','L’exposition aux gouttelettes','التعرض للرذاذ'],
'sym_h2'=>['Symptoms to watch for','Symptômes à surveiller','أعراض يجب الانتباه لها'],
'sym_p'=>['Fever, cough, fatigue, shortness of breath, loss of taste or smell, muscle aches, sore throat, headache, congestion, nausea or diarrhea. Test and isolate promptly if you have any of them.','Fièvre, toux, fatigue, essoufflement, perte du goût ou de l’odorat, courbatures, mal de gorge, maux de tête, congestion, nausées ou diarrhée. Faites un test et isolez-vous rapidement.','حمى، سعال، إرهاق، ضيق تنفس، فقدان الذوق أو الشم، آلام عضلية، التهاب الحلق، صداع، احتقان، غثيان أو إسهال. أجرِ الفحص وعزل نفسك فورًا عند ظهور أي منها.'],
'sym1_t'=>['High fever','Forte fièvre','حمى مرتفعة'],'sym1_p'=>['Usually above 38°C (100.4°F), often with chills and body aches.','Souvent supérieure à 38 °C, avec frissons et courbatures.','عادةً فوق 38°م، وغالبًا مع قشعريرة وآلام في الجسم.'],
'sym2_t'=>['Cough','Toux','سعال'],'sym2_p'=>['Dry or productive, and it can worsen over time.','Sèche ou grasse, elle peut s’aggraver avec le temps.','جاف أو مصحوب ببلغم، وقد يزداد سوءًا مع الوقت.'],
'sym3_t'=>['Sore throat','Mal de gorge','التهاب الحلق'],'sym3_p'=>['Pain or scratchiness, sometimes with difficulty swallowing.','Douleur ou irritation, parfois avec difficulté à avaler.','ألم أو خشونة، وأحيانًا صعوبة في البلع.'],
'sym4_t'=>['Headache','Maux de tête','صداع'],'sym4_p'=>['Persistent or severe, often felt as pressure or aching.','Persistants ou intenses, ressentis comme une pression.','مستمر أو شديد، يُشعَر به كضغط أو ألم.'],
'login_h'=>['Doctor login','Connexion médecin','دخول الأطباء'],'login_p'=>['Sign in to register patients and view predictions.','Connectez-vous pour enregistrer des patients et voir les prédictions.','سجّل الدخول لإضافة المرضى وعرض التنبؤات.'],
'username'=>['Username','Nom d’utilisateur','اسم المستخدم'],'password'=>['Password','Mot de passe','كلمة المرور'],'login_btn'=>['Log in','Se connecter','دخول'],
'err_login'=>['Wrong username or password.','Nom d’utilisateur ou mot de passe incorrect.','اسم المستخدم أو كلمة المرور غير صحيحة.'],
'id_nat'=>['National ID','Numéro d’identité','رقم الهوية'],'choose'=>['Choose','Choisir','اختر'],'male'=>['Male','Homme','ذكر'],'female'=>['Female','Femme','أنثى'],
'dose1'=>['1st injection','1re injection','الحقنة الأولى'],'dose2'=>['2nd injection','2e injection','الحقنة الثانية'],'right_arm'=>['Right arm','Bras droit','الذراع الأيمن'],'left_arm'=>['Left arm','Bras gauche','الذراع الأيسر'],
'rep_h'=>['Report side effects','Déclarer des effets secondaires','التبليغ عن الآثار الجانبية'],'fx_label'=>['Side effects experienced','Effets secondaires ressentis','الآثار الجانبية التي ظهرت'],
'fx_other'=>['Other side effects (optional)','Autres effets (facultatif)','آثار جانبية أخرى (اختياري)'],'fx_other_ph'=>['Type a side effect not listed above','Saisissez un effet non listé ci-dessus','اكتب أثرًا جانبيًا غير مذكور أعلاه'],
'd_start'=>['Date it started','Date d’apparition','تاريخ الظهور'],'d_dur'=>['Duration (days)','Durée (jours)','المدة (بالأيام)'],'save_report'=>['Save report','Enregistrer','حفظ التبليغ'],
'ok_effects'=>['Side effects saved successfully.','Effets secondaires enregistrés avec succès.','تم حفظ الآثار الجانبية بنجاح.'],
'err_id_missing'=>['No patient was found with this ID.','Aucun patient ne correspond à ce numéro.','لا يوجد مريض بهذا الرقم.'],
'step_patient'=>['Patient','Patient','المريض'],'step_vacc'=>['Vaccination','Vaccination','التلقيح'],'step_hist'=>['Medical history','Antécédents','السوابق المرضية'],
'f_name'=>['Full name','Nom complet','الاسم الكامل'],'f_gender'=>['Gender','Sexe','الجنس'],'f_age'=>['Age','Âge','العمر'],'f_addr'=>['Address','Adresse','العنوان'],'f_phone'=>['Phone','Téléphone','الهاتف'],
'f_vaccine'=>['Vaccine','Vaccin','اللقاح'],'f_dose'=>['Dose','Dose','الجرعة'],'f_batch'=>['Batch number','N° de lot','رقم الدفعة'],'f_expiry'=>['Expiry date','Date de péremption','تاريخ الصلاحية'],
'f_vacdate'=>['Vaccination date','Date de vaccination','تاريخ التلقيح'],'f_time'=>['Time','Heure','الوقت'],'f_loc'=>['Location','Lieu','المكان'],'f_site'=>['Injection site','Site d’injection','موضع الحقن'],
'hist_help'=>['Select every condition that applies. “No Background” clears when you pick another.','Cochez toutes les maladies concernées. « No Background » se décoche si vous en choisissez une autre.','اختر كل الحالات المنطبقة. يُلغى خيار «لا سوابق» عند اختيار غيره.'],
'hist_other'=>['Other conditions (optional)','Autres maladies (facultatif)','حالات أخرى (اختياري)'],
'hist_other_ph'=>['Type a condition not listed above','Saisissez une maladie non listée ci-dessus','اكتب حالة غير مذكورة أعلاه'],
'add_row'=>['Add another','Ajouter une autre','إضافة أخرى'],'rm_row'=>['Remove','Retirer','إزالة'],
'back'=>['Back','Retour','رجوع'],'cont'=>['Continue','Continuer','متابعة'],'save_cont'=>['Save and continue','Enregistrer et continuer','حفظ ومتابعة'],
'err_required'=>['All fields are required.','Tous les champs sont obligatoires.','جميع الحقول مطلوبة.'],'err_id_exists'=>['This ID number already exists.','Ce numéro d’identité existe déjà.','رقم الهوية موجود مسبقًا.'],
'ok_added'=>['Patient information saved successfully.','Informations du patient enregistrées avec succès.','تم حفظ معلومات المريض بنجاح.'],'err_generic'=>['Something went wrong. Please try again.','Une erreur est survenue. Veuillez réessayer.','حدث خطأ. يرجى المحاولة مرة أخرى.'],
'added_h'=>[':name was added',':name a été ajouté(e)','تمت إضافة :name'],'season'=>['Season','Saison','الموسم'],'med_hist'=>['Medical history','Antécédents médicaux','السوابق المرضية'],
'predict_btn'=>['Predict side effects','Prédire les effets secondaires','التنبؤ بالآثار الجانبية'],'add_another'=>['Add another patient','Ajouter un autre patient','إضافة مريض آخر'],
'res_title'=>['Predicted side effects','Effets secondaires prédits','الآثار الجانبية المتوقعة'],'most_likely'=>['Most likely side effect','Effet le plus probable','الأثر الجانبي الأكثر احتمالًا'],
'most_likely_for'=>['Most likely side effect for :name','Effet le plus probable pour :name','الأثر الأكثر احتمالًا لدى :name'],
'res_note'=>['Share of reported cases in the patient’s cluster, averaged across :n models. Bars are drawn at a 50% full scale.','Part des cas déclarés dans le groupe du patient, moyenne de :n modèles. Les barres sont tracées sur une échelle de 50 %.','نسبة الحالات المبلّغ عنها في مجموعة المريض، بمتوسط :n نماذج. الأشرطة مرسومة على مقياس 50٪.'],
'no_pred'=>['No prediction to show. Register a patient, then choose “Predict side effects”.','Aucune prédiction à afficher. Enregistrez un patient puis choisissez « Prédire les effets secondaires ».','لا يوجد تنبؤ لعرضه. سجّل مريضًا ثم اختر «التنبؤ بالآثار الجانبية».'],'back_patients'=>['Back to patients','Retour aux patients','العودة إلى المرضى'],
'pat_title'=>['Patients','Patients','المرضى'],'kpi_total'=>['Patients registered','Patients enregistrés','المرضى المسجلون'],'kpi_reported'=>['With side effects reported','Avec effets déclarés','مع آثار جانبية مبلّغ عنها'],
'kpi_follow'=>['Follow-up completed','Suivi complété','المتابعة المكتملة'],'kpi_vaccine'=>['Most used vaccine','Vaccin le plus utilisé','اللقاح الأكثر استخدامًا'],
'search_ph'=>['Search by name, ID or side effect','Rechercher par nom, numéro ou effet','ابحث بالاسم أو الرقم أو الأثر الجانبي'],'all_vaccines'=>['All vaccines','Tous les vaccins','كل اللقاحات'],
'th_patient'=>['Patient','Patient','المريض'],'th_age'=>['Age','Âge','العمر'],'th_vaccine'=>['Vaccine','Vaccin','اللقاح'],'th_fx'=>['Side effects','Effets secondaires','الآثار الجانبية'],'th_added'=>['Added','Ajouté le','تاريخ الإضافة'],
'not_reported'=>['Not reported yet','Pas encore déclarés','لم يُبلّغ بعد'],'no_patients'=>['No patients found.','Aucun patient trouvé.','لا يوجد مرضى.'],'add_first'=>['Add the first patient','Ajouter le premier patient','أضف أول مريض'],
'shown'=>['shown','affichés','معروض'],'top_fx'=>['Most reported side effects','Effets les plus déclarés','الآثار الأكثر تبليغًا'],'chart_empty'=>['Charts appear once side effects are reported.','Les graphiques apparaîtront dès que des effets seront déclarés.','تظهر الرسوم عند التبليغ عن آثار جانبية.'],
'unknown'=>['Unknown','Inconnu','غير معروف'],'sec_patient'=>['Patient','Patient','المريض'],'sec_vacc'=>['Vaccination','Vaccination','التلقيح'],'nf_h'=>['Patient not found','Patient introuvable','المريض غير موجود'],
'nf_p'=>['No patient has the ID “:id”.','Aucun patient n’a le numéro « :id ».','لا يوجد مريض بالرقم «:id».'],'rep_fx'=>['Reported side effects','Effets secondaires déclarés','الآثار الجانبية المبلّغ عنها'],
'started'=>['Started','Début','البداية'],'duration'=>['Duration','Durée','المدة'],'days'=>['days','jours','أيام'],'nothing'=>['Nothing reported yet.','Rien de déclaré pour l’instant.','لم يُبلّغ عن شيء بعد.'],
'today'=>['Today','Aujourd’hui','اليوم'],'clear'=>['Clear','Effacer','مسح'],'now'=>['Now','Maintenant','الآن'],'done'=>['Done','OK','تم'],'hour'=>['Hour','Heure','ساعة'],'minute'=>['Min','Min','دقيقة'],
'pick_date'=>['Select a date','Choisir une date','اختر تاريخًا'],'pick_time'=>['Select a time','Choisir l’heure','اختر الوقت'],
];
// Display names for stored data values. Keys are normalised (lower-case, no accents). Format: [English, French (null = keep stored), Arabic].
$D = [
'douleurs musculaires'=>['Muscle pain',null,'آلام العضلات'],'diarhee'=>['Diarrhea','Diarrhée','إسهال'],'diarrhee'=>['Diarrhea','Diarrhée','إسهال'],'fatigue'=>['Fatigue',null,'إرهاق'],'fievre'=>['Fever','Fièvre','حمى'],
'frisson'=>['Chills','Frissons','قشعريرة'],'insomnie'=>['Insomnia',null,'أرق'],'maux de tete'=>['Headache','Maux de tête','صداع'],'nausees'=>['Nausea','Nausées','غثيان'],'neuralgie'=>['Neuralgia','Névralgie','ألم عصبي'],'neveralgie'=>['Neuralgia','Névralgie','ألم عصبي'],
'palpitation'=>['Palpitations',null,'خفقان'],'toux'=>['Cough','Toux','سعال'],'troubles digestifs'=>['Digestive disorders',null,'اضطرابات هضمية'],'vertige'=>['Vertigo',null,'دوار'],'allergie cutanee'=>['Skin allergy','Allergie cutanée','حساسية جلدية'],
'ecoulement'=>['Discharge','Écoulement','إفرازات'],'meningite'=>['Meningitis','Méningite','التهاب السحايا'],'metrorragie'=>['Metrorrhagia','Métrorragie','نزيف رحمي'],'syndrom grippal'=>['Flu-like syndrome','Syndrome grippal','أعراض شبيهة بالإنفلونزا'],
'anemie'=>['Anemia','Anémie','فقر الدم'],'arthrose'=>['Osteoarthritis',null,'خشونة المفاصل'],'allergie'=>['Allergy',null,'حساسية'],'cardiaque'=>['Heart disease','Cardiaque','أمراض القلب'],'colopathie'=>['Colopathy',null,'اعتلال القولون'],
'diabete type 1'=>['Type 1 diabetes','Diabète type 1','السكري من النوع 1'],'diabete type 2'=>['Type 2 diabetes','Diabète type 2','السكري من النوع 2'],'dyslipidemie'=>['Dyslipidemia','Dyslipidémie','اضطراب شحوم الدم'],
'gastrite'=>['Gastritis',null,'التهاب المعدة'],'hemiplegie'=>['Hemiplegia','Hémiplégie','الشلل النصفي'],'hypothyroidie'=>['Hypothyroidism','Hypothyroïdie','قصور الغدة الدرقية'],'insuffisance renale'=>['Kidney failure','Insuffisance rénale','قصور كلوي'],
'rhinite allergique'=>['Allergic rhinitis',null,'التهاب الأنف التحسسي'],'varices'=>['Varicose veins',null,'دوالي'],'no background'=>['No background','Aucun antécédent','لا سوابق'],
'astra zeneca'=>['Astra Zeneca',null,'أسترازينيكا'],'sinopharm'=>['Sinopharm',null,'سينوفارم'],'sinovac'=>['Sinovac',null,'سينوفاك'],'sputnik-v-'=>['Sputnik V',null,'سبوتنيك V'],
'male'=>['Male','Homme','ذكر'],'female'=>['Female','Femme','أنثى'],'right'=>['Right arm','Bras droit','الذراع الأيمن'],'left'=>['Left arm','Bras gauche','الذراع الأيسر'],
'1st'=>['1st injection','1re injection','الحقنة الأولى'],'2nd'=>['2nd injection','2e injection','الحقنة الثانية'],'spring'=>['Spring','Printemps','الربيع'],'summer'=>['Summer','Été','الصيف'],'autumn'=>['Autumn','Automne','الخريف'],'fall'=>['Autumn','Automne','الخريف'],'winter'=>['Winter','Hiver','الشتاء'],
];
